default_module: 01KQY8QZ6GZHK04WVY2N78FBT1
includes:
  - modules/main.yaml
  - modules/android.yaml
  - modules/desktop.yaml
  - modules/core.yaml
kynetic: "1.1"
project:
  status: stable
  name: LocalBooru
  version: 0.3.11
task_storage:
  format: split
