_ulid: 01KXNWP3TCW36Y0BG80QVMJBWX
slugs:
  - task-curation-game
title: Implement Curation Game add-on
type: task
spec_ref: "@curation-game"
derivation: auto
status: in_progress
blocked_by: []
depends_on: []
context: []
priority: 1
tags:
  - gallery
  - addons
  - curation
vcs_refs: []
history:
  - author: DonutsDelivery
    changes:
      status:
        new: in_progress
        previous: pending
      started_at:
        new: 2026-07-16T16:38:26.549Z
        previous: null
    command: task-start
    timestamp: 2026-07-16T16:38:26.550Z
created_at: 2026-07-16T16:38:17.676Z
started_at: 2026-07-16T16:38:26.549Z
todos: []
