_ulid: 01KKEB00M6M6Y2N8CHA05C68RD
slugs: []
title: "Fix: ServerSettings QR scan does not perform handshake to get JWT token"
type: bug
spec_ref: null
meta_ref: null
plan_ref: null
status: pending
blocked_by: []
depends_on: []
context: []
priority: 2
tags: []
vcs_refs: []
created_at: 2026-03-11T11:37:28.454Z
todos: []
