_ulid: 01KY05JF1J18KZF69D08FQDWFN
slugs:
  - task-grouped-folder-thumbnail-identity
title: "Implement: Grouped Folder Thumbnail Identity"
type: task
spec_ref: "@folder-thumbnail-route-identity"
derivation: auto
status: pending_review
blocked_by: []
depends_on: []
context: []
priority: 1
tags: []
vcs_refs: []
submission_linkage:
  review_url: null
  branch: dispatch/task/implement-gsd-integration-retirement/01kxyrga
  captured_at: 2026-07-20T16:50:11.370Z
  commit: a1717951366c2b1aabaddf193ef1fe90cdd277f8
  remote: null
  remote_url: null
  upstream_ref: null
history:
  - author: DonutsDelivery
    changes:
      status:
        new: in_progress
        previous: pending
      started_at:
        new: 2026-07-20T16:26:13.666Z
        previous: null
    command: task-start
    timestamp: 2026-07-20T16:26:13.666Z
  - author: DonutsDelivery
    changes:
      status:
        new: pending_review
        previous: in_progress
      submission_linkage:
        new:
          review_url: null
          branch: dispatch/task/implement-gsd-integration-retirement/01kxyrga
          captured_at: 2026-07-20T16:50:11.370Z
          commit: a1717951366c2b1aabaddf193ef1fe90cdd277f8
          remote: null
          remote_url: null
          upstream_ref: null
        previous: null
      submitted_at:
        new: 2026-07-20T16:50:11.382Z
        previous: null
    command: task-submit
    timestamp: 2026-07-20T16:50:11.382Z
created_at: 2026-07-20T16:25:59.601Z
started_at: 2026-07-20T16:26:13.666Z
submitted_at: 2026-07-20T16:50:11.382Z
todos: []
