_ulid: 01KXQG5QXESKXQHBB7PFR2EPE3
slugs:
  - task-platform-add-on-dependencies
title: "Implement: Platform Add-on Dependencies"
type: task
spec_ref: "@addon-platform-dependencies"
derivation: auto
status: pending_review
blocked_by: []
depends_on: []
context: []
priority: 1
tags: []
vcs_refs: []
submission_linkage:
  review_url: null
  branch: v2
  captured_at: 2026-07-17T09:01:46.469Z
  commit: e3534e5e078b44eeefbe5ce5fab6b87cf2a9b604
  remote: origin
  remote_url: https://github.com/DonutsDelivery/LocalBooru.git
  upstream_ref: refs/heads/v2
history:
  - author: DonutsDelivery
    changes:
      status:
        new: in_progress
        previous: pending
      started_at:
        new: 2026-07-17T07:38:55.147Z
        previous: null
    command: task-start
    timestamp: 2026-07-17T07:38:55.147Z
  - author: DonutsDelivery
    changes:
      status:
        new: pending_review
        previous: in_progress
      submission_linkage:
        new:
          review_url: null
          branch: v2
          captured_at: 2026-07-17T09:01:46.469Z
          commit: e3534e5e078b44eeefbe5ce5fab6b87cf2a9b604
          remote: origin
          remote_url: https://github.com/DonutsDelivery/LocalBooru.git
          upstream_ref: refs/heads/v2
        previous: null
      submitted_at:
        new: 2026-07-17T09:01:46.473Z
        previous: null
    command: task-submit
    timestamp: 2026-07-17T09:01:46.473Z
created_at: 2026-07-17T07:38:07.150Z
started_at: 2026-07-17T07:38:55.147Z
submitted_at: 2026-07-17T09:01:46.473Z
todos: []
