_ulid: 01KXQG5QXESKXQHBB7PFR2EPE3
slugs:
  - task-platform-add-on-dependencies
title: "Implement: Platform Add-on Dependencies"
type: task
spec_ref: "@addon-platform-dependencies"
derivation: auto
status: pending
blocked_by: []
depends_on: []
context: []
priority: 1
tags: []
vcs_refs: []
created_at: 2026-07-17T07:38:07.150Z
todos: []
