_ulid: 01KXTTBR28AGG46E5SZ89WW42G
slugs:
  - task-desktop-launcher-continuity
title: "Implement: Desktop launcher continuity"
type: task
spec_ref: "@desktop-launcher-continuity"
derivation: auto
status: pending_review
blocked_by: []
depends_on: []
context: []
priority: 1
tags: []
vcs_refs: []
submission_linkage:
  review_url: null
  branch: dispatch/task/task-desktop-launcher-continuity/01kxttbr
  captured_at: 2026-07-18T15:11:17.628Z
  commit: 9604e44fc073f09b00728a98e6f81531c9b55cd7
  remote: origin
  remote_url: https://github.com/DonutsDelivery/LocalBooru.git
  upstream_ref: refs/heads/release/2.0.1
history:
  - author: DonutsDelivery
    changes:
      status:
        new: in_progress
        previous: pending
      started_at:
        new: 2026-07-18T14:34:09.282Z
        previous: null
    command: task-start
    timestamp: 2026-07-18T14:34:09.282Z
  - author: DonutsDelivery
    changes:
      status:
        new: pending_review
        previous: in_progress
      submission_linkage:
        new:
          review_url: null
          branch: dispatch/task/task-desktop-launcher-continuity/01kxttbr
          captured_at: 2026-07-18T15:11:17.628Z
          commit: 9604e44fc073f09b00728a98e6f81531c9b55cd7
          remote: origin
          remote_url: https://github.com/DonutsDelivery/LocalBooru.git
          upstream_ref: refs/heads/release/2.0.1
        previous: null
      submitted_at:
        new: 2026-07-18T15:11:17.635Z
        previous: null
    command: task-submit
    timestamp: 2026-07-18T15:11:17.635Z
created_at: 2026-07-18T14:33:52.968Z
started_at: 2026-07-18T14:34:09.282Z
submitted_at: 2026-07-18T15:11:17.635Z
todos: []
